In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("calisanlar.csv")

In [5]:
df

  calisanlar  maaslar
0        Ali     5000
1       Veli     6000
2       Ayse     7000

In [6]:
student = [
    {"calisanlar": "mehemmedeli", "maaslar": "7000"},
    {"calisanlar": "mehemmed", "maaslar": "8000"}
]

In [7]:
df = pd.DataFrame(student)

In [8]:
df

    calisanlar maaslar
0  mehemmedeli    7000
1     mehemmed    8000

In [11]:
mellimler ={
    "calisanlar": ["aygul","gunay"],
    "Surname": ["khanli", "Bayramli"]
}

In [12]:
df = pd.DataFrame(mellimler)

In [13]:
df

  calisanlar   Surname
0      aygul    khanli
1      gunay  Bayramli

In [14]:
df['suname']

KeyError: 'suname'

In [15]:
df[surname]

NameError: name 'surname' is not defined

In [16]:
df['Surname']

0      khanli
1    Bayramli
Name: Surname, dtype: str

In [17]:
type(df['Surname'])

pandas.Series

In [18]:
df.surname

AttributeError: 'DataFrame' object has no attribute 'surname'

In [19]:
df.Surname

0      khanli
1    Bayramli
Name: Surname, dtype: str

In [20]:
df[
    ['calisanlar', 'Surname']
]

  calisanlar   Surname
0      aygul    khanli
1      gunay  Bayramli

In [21]:
df.columns

Index(['calisanlar', 'Surname'], dtype='str')

In [22]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [23]:
df.iloc[1]

calisanlar       gunay
Surname       Bayramli
Name: 1, dtype: str

In [24]:
df.index= df.index +5

In [25]:
df.iloc[1]

calisanlar       gunay
Surname       Bayramli
Name: 6, dtype: str

In [26]:
df.loc[1]

KeyError: 1

In [27]:
df.loc[5]

calisanlar     aygul
Surname       khanli
Name: 5, dtype: str

In [28]:
df.shape

(2, 2)